[package]
name = "frontend"
version = "0.1.0"
authors = ["inanna malick <inanna@recursion.wtf>"]
edition = "2018"

[dependencies]
embed-wasm = { path = "../embed-wasm" }
phf = "0.8.0"

[build-dependencies]
embed-wasm-build = { path = "../embed-wasm-build"}
