version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:stretch
    steps:
      - checkout
      - run:
          name: Version Information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install Rust Components
          command: |
            rustup component add rustfmt
      - run:
          name: Setup Env
          command: |
            echo 'export RUSTFLAGS="-D warnings"' >> $BASH_ENV
      - run:
          name: Linting
          command: |
            cargo fmt -- --check
      - run:
          name: Build and Test
          command: |
            cargo build

  # docs-build and docs-deploy are adapted from
  # https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/.
  docs-build:
    docker:
      - image: circleci/rust:stretch
    steps:
      - checkout
      - run:
          name: Version Information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Generate documentation
          command: |
            cargo doc
      - persist_to_workspace:
          root: target
          paths: doc

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run:
          name: Disable jekyll builds
          command: touch target/doc/.nojekyll
      - run:
          name: Install and configure gh-pages
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "inanna+ci-build@recursion.wtf"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "9d:e4:1d:79:2b:62:0d:f6:8e:71:56:b8:a1:11:bb:0c"
      - run:
          name: Deploy to gh-pages branch
          command: |
            gh-pages --dotfiles --message "[skip ci] documentation update" --dist target/doc

workflows:
  version: 2
  build:
    jobs:
      - build
      - docs-build
      - docs-deploy:
          requires:
            - build
            - docs-build
          # filters:
          #   branches:
          #     only: master
