[package]
name = "app"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
my-types = { path = "../../my-types" }
serde = "1"
serde_derive = "1"
stdweb = "0.4"
yew = { version = "0.14", features = ["std_web"] }

# empty workspace
[workspace]