[package]
name = "my-frontend"
version = "0.1.0"
authors = ["inanna malick <inanna@recursion.wtf>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"

[build-dependencies]
ignore = "0.4.14"
cargo-web = "=0.6.26"
structopt = "0.2"